apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-secret-bank-app
  labels:
    tier: database
    app: bank-app
data:
  POSTGRES_DB: "bank_app_db_test"
  POSTGRES_USER: "bank_app_user"
  POSTGRES_PASSWORD: "bank_app_pwd"