apiVersion: v1
kind: Service
metadata:
  name: postgres-service-bank-app
spec:
  type: LoadBalancer
  selector:
    app: bank-app-database
  ports:
    - name: db-svc-port
      protocol: TCP
      port: 5433
      targetPort: app-db-prt
