apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-volume-claim-bank-app
  labels:
    app: bank-app
    tier: database
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi