apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bank-app-database
  template:
    metadata:
      labels:
        app: bank-app-database
    spec:
      containers:
        - name: postgres
          image: 'postgres:12'
          imagePullPolicy: IfNotPresent
          ports:
            - name: app-db-prt
              containerPort: 5432
          envFrom:
            - configMapRef:
                name: postgres-secret-bank-app
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgresdata
      volumes:
        - name: postgresdata
          persistentVolumeClaim:
            claimName: postgres-volume-claim-bank-app